package rmi.view;

//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import java.io.IOException;

import javax.swing.*;
import javax.swing.event.*;

import rmi.RmiClient;

public class view extends JPanel {
	private JTextField	jcomp1;
	private JButton			send;
	private JMenuBar		jcomp3;
	private JPanel			msgs;
	private  RmiClient CLIENT = null;
	
	public view() {
		// construct preComponents
		JMenu fileMenu = new JMenu("File");
		JMenuItem exitItem = new JMenuItem("Exit");
		
		exitItem.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent e) {
				System.exit(0);
			}
		});
		
		fileMenu.add(exitItem);
		JMenu chatMenu = new JMenu("Chat");
		JMenuItem connectItem = new JMenuItem("Connect");
		
		connectItem.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent e) {
				
			}
		});
		
		chatMenu.add(connectItem);
		JMenuItem disconnectItem = new JMenuItem("Disconnect");
		
		disconnectItem.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent e) {
				
			}
		});
		
		chatMenu.add(disconnectItem);
		JMenu helpMenu = new JMenu("Help");
		JMenuItem aboutItem = new JMenuItem("About");
		
		aboutItem.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent e) {
				
			}
		});
		
		helpMenu.add(aboutItem);
		JMenuItem versionItem = new JMenuItem("Version");
		
		versionItem.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent e) {
				
			}
		});
		
		helpMenu.add(versionItem);
		
		// construct components
		jcomp1 = new JTextField(5);
		send = new JButton("SEND");
		jcomp3 = new JMenuBar();
		jcomp3.add(fileMenu);
		jcomp3.add(chatMenu);
		jcomp3.add(helpMenu);
		
		// set components properties
		jcomp1.setToolTipText("Schreib deine Nachricht :)");
		send.setToolTipText("Die Nachricht senden");
		
		// JPanel
		msgs = new JPanel();
		
		// Jscrollpane für Messages
		JScrollPane scrollPane = new JScrollPane(msgs,
				ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS,
				ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
		
		// adjust size and set layout
		setPreferredSize(new Dimension(370, 410));
		setLayout(null);
		
		// Action Listener send button
		send.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent e) {
				try {
					CLIENT.getInstance().sendMessage("HI");
					if(CLIENT instanceof RmiClient) {
					System.out.println("Korrekt");
					} else {
						System.out.println("Nein");
					}
				} catch (IOException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}
			}
		});
		
		
		// add components
		add(jcomp1);
		add(scrollPane);
		add(send);
		add(jcomp3);
		
		// set component bounds (only needed by Absolute Positioning)
		scrollPane.setBounds(10, 45, 360, 325);
		jcomp1.setBounds(10, 380, 260, 25);
		send.setBounds(275, 380, 95, 25);
		jcomp3.setBounds(0, 0, 385, 30);
	}
	
	public static void main(String[] args) {
		JFrame frame = new JFrame("Niggos RMI Chat");
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		frame.getContentPane().add(new view());
		frame.pack();
		frame.setVisible(true);
		frame.setResizable(false);
	}
}
